# ── Backend ───────────────────────
backend = "xrender"
vsync = true

# ── Window Settings ───────────────
corner-radius = 0
detect-client-opacity = true
detect-transient = true
use-damage = false
log-level = "warn"

# ── Animations ────────────────────
animations = true;
animation-stiffness = 200;
animation-dampening = 25;
animation-window-mass = 0.5;
animation-for-open-window = "slide-up";
animation-for-unmap-window = "zoom";

# ── Fading ────────────────────────
fading = true
fade-delta = 5
fade-in-step = 0.03
fade-out-step = 0.03

# ── Shadow ────────────────────────
shadow = true
shadow-radius = 7
shadow-offset-x = -7
shadow-offset-y = -7
shadow-opacity = 0.5

# ── Opacity ───────────────────────
active-opacity = 1.0
inactive-opacity = 0.95

wintypes:
{
  dock = { shadow = false; };
  dnd = { shadow = false; };
  popup_menu = { opacity = 1.0; };
  dropdown_menu = { opacity = 1.0; };
};
