; Gruvbox Polybar Configuration

[bar/gruvbox-main]
width = 100%
height = 32
radius = 10
fixed-center = true

background = ${color.BACKGROUND}
foreground = ${color.FOREGROUND}

border-size = 0
border-color = #00000000

padding-left = 2
padding-right = 2
module-margin-left = 1
module-margin-right = 1

font-0 = JetBrainsMono Nerd Font:size=9:antialias=false;0
font-1 = JetBrainsMono Nerd Font:size=9:antialias=false;0
font-2 = JetBrainsMono Nerd Font:size=9:antialias=false;0

modules-left = archlogo
modules-center = xwindow
modules-right = date time powermenu

[tray-mode]
cursor-click = pointer

[settings]
screenchange-reload = true
enable-ipc = true

[module/archlogo]
type = custom/text
content = ""
content-font = 2
content-foreground = ${color.RED}
content-background = ${color.BACKGROUND}
padding-left = 1
padding-right = 1

[module/xwindow]
type = internal/xwindow
label = "%title:0:30:...%"
label-foreground = ${color.FOREGROUND}
label-background = ${color.BACKGROUND}
padding-left = 1
padding-right = 1

[module/date]
type = internal/date
date = "%a %d %b"
date-font = 2
date-foreground = ${color.GREEN}
date-background = ${color.BACKGROUND}
padding-left = 1
padding-right = 1

[module/time]
type = internal/date
date = "%H:%M"
date-font = 2
date-foreground = ${color.YELLOW}
date-background = ${color.BACKGROUND}
padding-left = 1
padding-right = 1

[module/powermenu]
type = custom/menu
content = ""
content-font = 2
content-foreground = ${color.MAGENTA}
content-background = ${color.BACKGROUND}
padding-left = 1
padding-right = 1
click-right = ~/.config/polybar/gruvbox/powermenu.sh