# ===== FONT =====
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        10.0
disable_ligatures cursor

# ===== CURSOR =====
cursor            #fe8019
cursor_text_color #282828
cursor_shape      beam
cursor_blink_interval 1
cursor_trail 4

# ===== BACKGROUND & TEXT =====
background #282828
background_opacity 0.80
foreground #ebdbb2

# ===== SELECTION =====
selection_background #504945
selection_foreground #ebdbb2

# ===== BORDER =====
active_border_color   #fe8019
inactive_border_color #3c3836

# ===== URL =====
url_color #d65d0e

# ===== WINDOW =====
window_padding_width 6
scrollback_lines 2000

# ===== SCROLLBAR =====
scrollbar never

# ===== ANSI COLORS =====

# Black
color0  #282828
color8  #928374

# Red
color1  #cc241d
color9  #fb4934

# Green
color2  #98971a
color10 #b8bb26

# Yellow
color3  #d79921
color11 #fabd2f

# Blue
color4  #458588
color12 #83a598

# Magenta
color5  #b16286
color13 #d3869b

# Cyan
color6  #689d6a
color14 #8ec07c

# White
color7  #a89984
color15 #ebdbb2
