[bar/hutao-main]
monitor = 
width = 96%
height = 28
offset-x = 2%
offset-y = 8
background = #1a1a1a
foreground = #ffffff
radius = 10
override-redirect = true
wm-restack = bspwm
padding = 1
font-0 = "JetBrainsMono Nerd Font:size=9;2"

modules-left = arch sep workspace add-ws sep prev next sep filesystem
modules-center = date
modules-right = cpu sep memory sep powermenu

; --- Polybar Avoidance ---
monitor-strict = false
enable-ipc = true
fixed-center = true
border-size = 1
; -------------------------

[module/workspace]
type = internal/bspwm
label-active = " 󰮯 "
label-active-foreground = #c0392b
label-occupied = " 󰊠 "
label-occupied-foreground = #ffffff
label-urgent = " 󰊠 "
label-urgent-foreground = #c0392b
label-empty = " 󰊠 "
label-empty-foreground = #444
label-separator = " "

[module/add-ws]
type = custom/text
content = "  "
content-foreground = #d4a017
click-left = ~/.config/polybar/toggle_ws.sh

[module/sep]
type = custom/text
content = " | "
content-foreground = #444

[module/arch]
type = custom/text
content = "  "
content-foreground = #1793d1
click-left = rofi -no-config -theme $HOME/.local/share/rofi/themes/simple-tokyonight.rasi -show drun &

[module/prev]
type = custom/text
content = " 󰁍 "
content-foreground = #ffffff
click-left = bspc desktop -f prev.local

[module/next]
type = custom/text
content = " 󰁔 "
content-foreground = #ffffff
click-left = bspc desktop -f next.local

[module/filesystem]
type = internal/fs
interval = 30
mount-0 = /
label-mounted =  %percentage_used%%
label-unmounted = 
label-mounted-foreground = #d4a017

[module/date]
type = internal/date
date = %H:%M
label = " | %date% | "
label-foreground = #f5d5c0

[module/cpu]
type = internal/cpu
label =  %percentage%%

[module/memory]
type = internal/memory
label =  %percentage_used%%

[module/powermenu]
type = custom/text
content = " ⏻ "
content-font = 1
content-foreground = #c0392b
click-left = eww open --toggle powermenu
